param(
    [switch]$SkipMermaid,
    [switch]$ForceMermaid,
    [string]$OutputPath
)

$ErrorActionPreference = "Stop"

function Add-MiKTeXToPath {
    $miktexBin = Join-Path $env:USERPROFILE "scoop\apps\miktex\current\texmfs\install\miktex\bin\x64"
    if ((Test-Path -LiteralPath $miktexBin -PathType Container) -and -not ($env:PATH.Split(";") -contains $miktexBin)) {
        $env:PATH = "$miktexBin;$env:PATH"
    }
}

function Resolve-ProjectPath {
    param([string]$Path)

    if ([string]::IsNullOrWhiteSpace($Path)) {
        return $null
    }
    if ([System.IO.Path]::IsPathRooted($Path)) {
        return [System.IO.Path]::GetFullPath($Path)
    }
    return [System.IO.Path]::GetFullPath((Join-Path $ProjectRoot $Path))
}

function Write-BodyOnlyCites {
    $referencesPath = Join-Path $ProjectRoot "chapters\references.tex"
    $outputDir = Join-Path $ProjectRoot "dist"
    $citationOutputPath = Join-Path $outputDir "body-only-cites.tex"

    if (-not (Test-Path -LiteralPath $referencesPath -PathType Leaf)) {
        throw "References file not found: $referencesPath"
    }
    if (-not (Test-Path -LiteralPath $outputDir -PathType Container)) {
        New-Item -ItemType Directory -Path $outputDir | Out-Null
    }

    $content = Get-Content -LiteralPath $referencesPath -Raw -Encoding UTF8
    $matches = [regex]::Matches($content, "\\bibitem(?:\[[^\]]*\])?\{([^{}]+)\}")
    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add("% Generated by scripts/build-body.ps1. Do not edit manually.")
    $lines.Add("\makeatletter")

    $index = 1
    foreach ($match in $matches) {
        $key = $match.Groups[1].Value
        $lines.Add("\bibcite{$key}{$index}")
        $index += 1
    }

    $lines.Add("\makeatother")
    Set-Content -LiteralPath $citationOutputPath -Value $lines -Encoding UTF8
    Write-Host "[body] generated citation labels: $citationOutputPath"
}

$ProjectRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
Set-Location $ProjectRoot
Add-MiKTeXToPath

if (-not $SkipMermaid) {
    $mermaidArgs = @("-AllowFallback")
    if ($ForceMermaid) {
        $mermaidArgs += "-Force"
    }
    & (Join-Path $PSScriptRoot "render-mermaid.ps1") @mermaidArgs
}

Write-BodyOnlyCites

$latexmk = Get-Command latexmk -ErrorAction SilentlyContinue
if ($null -eq $latexmk) {
    throw "latexmk not found. Install latexmk, then retry."
}

$oldSkip = $env:ZUST_SKIP_LATEX_PREPARE
$env:ZUST_SKIP_LATEX_PREPARE = "1"
try {
    & $latexmk.Source -xelatex -interaction=nonstopmode -file-line-error main-body.tex
    $exitCode = $LASTEXITCODE
}
finally {
    if ($null -eq $oldSkip) {
        Remove-Item Env:\ZUST_SKIP_LATEX_PREPARE -ErrorAction SilentlyContinue
    }
    else {
        $env:ZUST_SKIP_LATEX_PREPARE = $oldSkip
    }
}

if ($exitCode -eq 0 -and -not [string]::IsNullOrWhiteSpace($OutputPath)) {
    $resolvedOutput = Resolve-ProjectPath -Path $OutputPath
    $outputDir = Split-Path -Parent $resolvedOutput
    if (-not (Test-Path -LiteralPath $outputDir -PathType Container)) {
        New-Item -ItemType Directory -Path $outputDir | Out-Null
    }
    Copy-Item -LiteralPath (Join-Path $ProjectRoot "main-body.pdf") -Destination $resolvedOutput -Force
    Write-Host "[body] copied PDF: $resolvedOutput"
}

exit $exitCode
